NT_WRITE_FILE_ADDRESS               equ 0x12345678
NT_QUERY_PERF_COUNTER_ADDRESS       equ 0x12345678
RTL_QUERY_PERF_COUNTER_ADDRESS      equ 0x12345678
LOG_FILE_HANDLE                     equ 0x12345678
API_INFO_ADDRESS                    equ 0x12345678

SIZEOF_PIO_STATUS_BLOCK             equ     8h
TEB_PPEB_OFFSET                     equ     30h
TEB_THREADID_OFFSET                 equ     24h
PEB_PLDR_OFFSET                     equ     0ch
LDR_PIN_ORDER_MOD_LIST_OFFSET       equ     0ch
LDR_MODULE_BASE_OFFSET              equ     18h
LDR_MODULE_NAME_OFFSET              equ     2ch
LDR_SIZE_OF_IMAGE_OFFSET            equ     20h