NT_WRITE_FILE_ADDRESS               equ 0x1234567812345678
NT_QUERY_PERF_COUNTER_ADDRESS       equ 0x1234567812345678
RTL_QUERY_PERF_COUNTER_ADDRESS      equ 0x1234567812345678
LOG_FILE_HANDLE                     equ 0x1234567812345678
API_INFO_ADDRESS                    equ 0x1234567812345678
MAIN_MODULE_BASE                    equ 0x1234567812345678
MAIN_MODULE_TOP                     equ 0x1234567812345678

SIZEOF_PIO_STATUS_BLOCK             equ     10h
TEB_PPEB_OFFSET                     equ     60h
TEB_THREADID_OFFSET                 equ     48h
PEB_PLDR_OFFSET                     equ     18h
LDR_PIN_ORDER_MOD_LIST_OFFSET       equ     10h
LDR_MODULE_BASE_OFFSET              equ     30h
LDR_MODULE_NAME_OFFSET              equ     58h
LDR_SIZE_OF_IMAGE_OFFSET            equ     40h